version: '2'
services:
  web:
    restart: always
    build: .
    links:
    - db
    ports:
    - "80:5000"
    volumes:
      - .:/app
    dns:
    - 8.8.8.8

  db:
    image: postgres:10
    restart: always
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: "flaskapp_user"
      POSTGRES_PASSWORD: "flaskapp_pass"
      POSTGRES_DB: "flaskapp"

