version: '2'
services:
  web:
    restart: always
    build: .
    links:
    - db
    ports:
    - "5000:5000"
    volumes:
      - .:/app

  db:
    image: postgres:10
    restart: always
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: "flaskapp_user"
      POSTGRES_PASSWORD: "flaskapp_pass"
      POSTGRES_DB: "flaskapp"
#    volumes:
#      - ./postgres-data/postgres:/var/lib/postgresql/data